[package]
name = "pt3d"
version = "0.0.1"
authors = [ "Georgiy Shevoroshkin <gshevoroshkin@proton.me>" ]
license = "The Happy Bunny License (Modified MIT License)"
description = "3d plotting library"
repository = "https://github.com/omega-800/pt3d.git"
categories = [ "visualization" ]
keywords = [ "3d", "plot", "graph" ]
entrypoint = "lib/pt3d.typ"
compiler = "0.14.2"
exclude = [ "examples/*" ]
